import React,{useEffect,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {Wallet,TrendingUp,TrendingDown,Plus,Trash2,LogOut} from 'lucide-react'
import './style.css'

const API=import.meta.env.VITE_API_URL||'http://localhost:8080/api'
const categories=['Food','Travel','Shopping','Education','Bills','Entertainment','Health','Other']

async function api(path,options={}){const res=await fetch(API+path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options}); const data=await res.json().catch(()=>null); if(!res.ok) throw new Error(data||'Request failed'); return data}

function Auth({onLogin}){
 const [mode,setMode]=useState('login'); const [form,setForm]=useState({name:'',email:'',password:''}); const [error,setError]=useState('')
 const submit=async e=>{e.preventDefault();setError('');try{const data=await api('/auth/'+mode,{method:'POST',body:JSON.stringify(form)});localStorage.setItem('user',JSON.stringify(data));onLogin(data)}catch(err){setError(err.message)}}
 return <div className="auth"><div className="auth-card"><div className="brand"><Wallet/> <span>Expense Tracker</span></div><h1>{mode==='login'?'Welcome back':'Create account'}</h1><p className="muted">Manage your money simply and clearly.</p><form onSubmit={submit}>{mode==='register'&&<input placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>}<input type="email" placeholder="Email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input type="password" placeholder="Password" required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>{error&&<div className="error">{error}</div>}<button className="primary">{mode==='login'?'Login':'Register'}</button></form><button className="link" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?"Don't have an account? Register":"Already have an account? Login"}</button></div></div>
}

function Dashboard({user,onLogout}){
 const [transactions,setTransactions]=useState([]); const [summary,setSummary]=useState({income:0,expense:0,balance:0}); const [form,setForm]=useState({type:'EXPENSE',amount:'',date:new Date().toISOString().slice(0,10),category:'Food',description:''}); const [error,setError]=useState('')
 const load=async()=>{try{const [t,s]=await Promise.all([api('/transactions/user/'+user.id),api('/transactions/user/'+user.id+'/summary')]);setTransactions(t);setSummary(s)}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[])
 const add=async e=>{e.preventDefault();setError('');try{await api('/transactions',{method:'POST',body:JSON.stringify({...form,userId:user.id,amount:Number(form.amount)})});setForm({...form,amount:'',description:''});load()}catch(e){setError(e.message)}}
 const remove=async id=>{await api('/transactions/'+id,{method:'DELETE'});load()}
 return <div className="app"><header><div className="brand"><Wallet/> Expense Tracker</div><div className="user">Hi, {user.name}<button onClick={onLogout} title="Logout"><LogOut size={18}/></button></div></header><main><section className="hero"><div><h1>Personal Finance Dashboard</h1><p>Track income, expenses and your remaining balance.</p></div></section><section className="cards"><div className="card"><span>Balance</span><strong>₹{Number(summary.balance).toFixed(2)}</strong><Wallet/></div><div className="card income"><span>Total Income</span><strong>₹{Number(summary.income).toFixed(2)}</strong><TrendingUp/></div><div className="card expense"><span>Total Expense</span><strong>₹{Number(summary.expense).toFixed(2)}</strong><TrendingDown/></div></section><section className="grid"><div className="panel"><h2><Plus size={20}/> Add Transaction</h2><form onSubmit={add} className="transaction-form"><div className="toggle"><button type="button" className={form.type==='EXPENSE'?'active':''} onClick={()=>setForm({...form,type:'EXPENSE'})}>Expense</button><button type="button" className={form.type==='INCOME'?'active income-btn':''} onClick={()=>setForm({...form,type:'INCOME'})}>Income</button></div><input type="number" min="0.01" step="0.01" placeholder="Amount" required value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><input type="date" required value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/>{form.type==='EXPENSE'?<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select>:<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Salary</option><option>Freelance</option><option>Business</option><option>Other</option></select>}<input placeholder="Description (optional)" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button className="primary">Add Transaction</button>{error&&<div className="error">{error}</div>}</form></div><div className="panel"><h2>Recent Transactions</h2>{transactions.length===0?<p className="empty">No transactions yet. Add your first one.</p>:<div className="transactions">{transactions.map(t=><div className="tx" key={t.id}><div><b>{t.category}</b><small>{t.date}{t.description?' · '+t.description:''}</small></div><strong className={t.type==='INCOME'?'plus':'minus'}>{t.type==='INCOME'?'+':'-'}₹{Number(t.amount).toFixed(2)}</strong><button onClick={()=>remove(t.id)}><Trash2 size={16}/></button></div>)}</div>}</div></section></main></div>
}

function App(){const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem('user')||'null')); if(!user)return <Auth onLogin={setUser}/>; return <Dashboard user={user} onLogout={()=>{localStorage.removeItem('user');setUser(null)}}/>}
createRoot(document.getElementById('root')).render(<App/>)
